export {default as Home} from "./Home/Home"
export {default as Products} from "./Products/Products"
export {default as About} from "./About/About"
export {default as Contact} from "./Contact/Contact"
export {default as PageNotFound} from "./PageNotFound/PageNotFound"
export  {default as NavBar } from "./NavBar/NavBar"